'''
Stokes problem on a unit square.
Poiseuille flow generated by a traction (pressure) difference.
Flow rate computation.
'''

import numpy as np
from scipy.sparse.linalg import spsolve
from func import func
from traction_func import traction_func
import eztfem as ezt


def main():
    """
    Returns
    -------
    flowrate : float
        Flow rate.
    mesh : Mesh
        Finite element mesh.
    problem : Problem
        Stokes problem definition.
    u : numpy.ndarray
        Nodal values of velocity and pressure (solution vector).
    derivs : dict
        Dictionary of derived fields (Vector instances).
    """

    # create mesh

    mesh = ezt.quadrilateral2d([2, 10], 'quad9')

    # define the problem

    elementdof = np.array([[2, 2, 2, 2, 2, 2, 2, 2, 2],
                           [1, 0, 1, 0, 1, 0, 1, 0, 0],
                           [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int).transpose()
    problem = ezt.Problem(mesh, elementdof, nphysq=2)

    # define Gauss integration and basis functions

    user = ezt.User()
    shape = 'quad'

    user.xr, user.wg = ezt.gauss_legendre(shape, num_int_points=3)

    user.phi, user.dphi = ezt.basis_function(shape, 'Q2', user.xr)

    user.psi, _ = ezt.basis_function(shape, 'Q1', user.xr)

    # user struct for setting problem coefficients, ...

    user.coorsys = 0
    user.mu = 1
    user.funcnr = 0
    user.func = func  # not used when funcnr == 0

    # assemble the system matrix and vector

    system_matrix, rhs = ezt.build_system(mesh, problem, ezt.stokes_elem, user)

    # define Gauss integration and basis functions (for boundary integral)

    [xr, user.wg] = ezt.gauss_legendre('line', num_int_points=3)

    [user.phi, user.dphi] = ezt.basis_function('line', 'P2', xr)

    # add natural boundary condition

    user.funcnr = 1
    user.func = traction_func
    ezt.add_boundary_elements(mesh, problem, rhs, ezt.stokes_natboun_curve,
                              user, physqrow=[0], curve=3)

    # define essential boundary conditions (Dirichlet)

    iess = ezt.define_essential(mesh, problem, 'curves', [0, 2], degfd=0)
    iess = ezt.define_essential(mesh, problem, 'curves', [0, 1, 2, 3], degfd=1,
                                iessp=iess)

    # zero bc values

    uess = np.zeros(problem.numdegfd)

    # apply essential boundary conditions to the system

    ezt.apply_essential(system_matrix, rhs, uess, iess)

    # solve the system

    u = spsolve(system_matrix.tocsr(), rhs)

    # flow rate

    user.u = u
    flowrate = ezt.integrate_boundary_elements(mesh,
                                               problem,
                                               ezt.stokes_flowrate_curve,
                                               user, curve=1)

    # pressure in all nodes for plotting

    xr = ezt.refcoor_nodal_points(mesh)
    user.psi, _ = ezt.basis_function('quad', 'Q1', xr)
    user.u = u
    derivs = {}
    derivs["pressure"] = ezt.deriv_vector(mesh, problem, ezt.stokes_pressure,
                                          user)

    # derivatives of the velocity

    xr = ezt.refcoor_nodal_points(mesh)
    user.phi, user.dphi = ezt.basis_function('quad', 'Q2', xr)
    user.u = u

    user.comp = 0  # dudx
    derivs["dudx"] = ezt.deriv_vector(mesh, problem, ezt.stokes_deriv, user)
    user.comp = 1  # dudy
    derivs["dudy"] = ezt.deriv_vector(mesh, problem, ezt.stokes_deriv, user)
    user.comp = 2  # dvdx
    derivs["dvdx"] = ezt.deriv_vector(mesh, problem, ezt.stokes_deriv, user)
    user.comp = 3  # dvdy
    derivs["dvdy"] = ezt.deriv_vector(mesh, problem, ezt.stokes_deriv, user)
    user.comp = 4  # dvdx - dudy = vorticity
    derivs["omega"] = ezt.deriv_vector(mesh, problem, ezt.stokes_deriv, user)
    user.comp = 6  # divu, divergence of the velocity field
    derivs["div_u"] = ezt.deriv_vector(mesh, problem, ezt.stokes_deriv, user)
    user.comp = 7  # gammadot, effective strain rate = sqrt(2II_D)
    derivs["gammadot"] = ezt.deriv_vector(mesh, problem, ezt.stokes_deriv,
                                          user)

    return flowrate, mesh, problem, u, derivs


if __name__ == '__main__':
    results = main()
    print('flowrate = ', results[0])
